<?php $schedule = array(
	'Monday' => array(
		//'vapour' => ['Vapour Esports', 'vapour-esports', 882, 'OCE - 2v2', '5AM EST'],
		//'rlrsSilent' => ['RLRS Matches', 'rlesports', 1033, 'Silent Stream', '12PM EST'],
		// 'baguette' => ['Rocket Baguette', 'rocket-baguette', 585, 'PGW Qualifiers', '2PM EST'],
		// 'rams' => ['GFinity Journey', 'rams', 1519, 'Method', '1PM EST'],
		'ballistix' => ['Ballistix Gaming', 'ballistix', 1372, 'EU - $3500 - Qualifiers', '1PM EST'],
		//'diamondDuels' => ['Diamond Duels', 'diamond-duels', 1177, 'EU - 1v1', '2PM EST'],
		'euroRL' => ['EuroRL', 'euro-rl', 1491, 'EU - Euro RL Series', '2PM EST'],
		'partTime' => ['Part Time Pros', 'parttimepros', 1417, 'EU - 3v3', '3PM EST'],
		//'Rival' => ['Rival Esports', 'prorl', 81, 'NA - 3v3 - $150', '7PM EST'],
		'vvv' => ['vVv', 'vvv-gaming', 239, "3v3 Captain's Draft", '8PM EST'],
		'rbg' => ['RBG Esports', 'rbg-esports', 1576, "NA - 3v3 - $60", "8PM EST"],
		//'ace' => ['ACE', 'ascending-champions', 928, 'NA - 2v2 Champ League', '8PM EST'],
		//'myth' => ['Primal League Open', 'mythical-esports', 251, 'NA - 3v3 - Placement', '8PM EST'],
		// 'memento' => ['Memento Mori', 'memento-mori', 1453, "NA - 3v3", '8PM EST'],
		//'bl' => ['Boost Legacy', 'boost-legacy', 401, 'NA - 1v1 - $20', '8PM EST'],
		'collegeRL' => ['College RL', 'rlcs', 79, 'League Play', '7PM EST'],
		'tartans' => ['Team Tartans', 'team-tartans', 1573, 'NA - 3v3', '9PM EST'],
		// 'astro' => ['ASTRONAUTS', 'teambeyondnet', 540, 'NA - 1v1 - $1,000', '930PM EST'],
		//'cca' => ['CCA', 'cca', 736, 'Monday Night Madness', '10PM EST'],
		'me' => ['The Dailies', 'rocket-dailies', 688, 'Nom Stream', '6PM EST'],
	),
	'Tuesday' => array(
		//'byza' => ['Community Cup', 'byza', 1171, 'OCE - 1v1 - $1000', '430AM EST'],
		// 'baguette' => ['Rocket Baguette', 'rocket-baguette', 585, 'Paris Games Week Finals', '5AM EST'],
		// 'rlo' => ['Rocket League Oceania', 'rocket-league-oceania', 646, 'OCE - 3v3 - $200', '5AM EST'],
		//'rlindia' => ['RLIndia', 'rlindia', 897, 'India - 3v3', '1030AM EST'],
		// 'gfinityEU' => ['GFinity (EU)', 'rocket-league-central', 547, 'EU - 3v3 - $250', '1PM EST'],
		// 'euccgg' => ['ECC', 'ecc', 1507, 'League Play', '1PM EST'],
		//'rlrsSilent' => ['RLRS Matches', 'rlesports', 1033, 'Silent Stream', '12PM EST'],
		//'universalOpen' => ['Universal Open', 'faceit', 883, 'EU Closed Quals', '12PM EST'],
		//'glory' => ['Glory4Gamers', 'glory4gamers', 848, 'EU - 3v3 &euro;30', '230PM EST'],
		//'arrow' => ['Arrow League', 'arrow-league', 1432, 'UK University League', '3PM EST'],
		//'nexus' => ['Nexus', 'nexus-gaming', 389, 'NA - 1v1 - $50', '7PM EST'],
		'rlpc' => ['RLPC', 'rlpc', 1495, 'NA - League Play', '7PM EST'],
		'collegeRL' => ['College RL', 'rlcs', 79, 'League Play', '7PM EST'],
		'elevate' => ['Elevate', 'elevate-league', 820, 'Challenger Series: Elevate Cup', '7PM EST'],
		//'forzen' => ['Forzen Esports', 'forzen', 772, 'NA - 2v2 - $20', '8PM EST'],
		//'myth' => ['Mythical Esports', 'mythical-esports', 251, 'Primal League - NA', '8PM EST'],
		//'collegeRL' => ['College RL', 'rlesports', 1033, 'Playoffs!', '8PM EST'],
		// 'playerOne' => ['Player One Esports', 'player-one-esports', 1500, 'NA - 2v2 - $1,000', '8PM EST'],
		'sway' => ['Sway Cup', 'sway-esports', 1152, 'NA - 3v3 - $30', '8PM EST'],
		'ppl' => ['Pulsar Premier League', 'ppl', 134, 'NA - 3v3 - $30', '8PM EST'],
		// 'cca' => ['CCA', 'cca', 736, 'Summer Series Playoffs', '9PM EST'],
		'me' => ['The Dailies', 'rocket-dailies', 688, 'Nom Stream', '6PM EST'],
	),
	'Wednesday' => array(
		//'throwdown' => ['Throwdown TV', 'throwdowntv', 531, 'OCE - Open Qualifiers', '5AM EST'],
		//'rlindia' => ['RLIndia', 'rlindia', 897, 'Asian Nations Cup Showmatches', '1030AM EST'],
		// 'universalOpen' => ['Universal Open', 'faceit', 883, 'EU Closed Qualifiers', '12PM EST'],
		//'gfinityEU' => ['GFinity EU', 'rocket-league-central', 547, 'EU - 3v3 Challenger Series', '1PM EST'],
		//'ireland' => ['RL Ireland', 'rocket-league-ireland', 1115, 'Nixus v All Stars', '2PM EST'],
		//'metaleak' => ['Metaleak', 'metaleak', 521, 'EU - &euro;500 Metacup', '2PM EST'],
		//'diamondDuels' => ['Diamond League', 'diamond-duels', 1177, 'EU - 2v2 - League Play', '2PM EST'],
		'euroRL' => ['EuroRL', 'euro-rl', 1491, 'EU - Euro RL Series', '2PM EST'],
		'rocketeers' => ['The Thunderdome', 'rocketeers', 1577, 'EU Renegade Cup', '1PM EST'],
		// 'arrow' => ['Arrow League', 'arrow-league', 1432, 'UK University League', '3PM EST'],
		// 'memento' => ['Memento Mori', 'memento-mori', 1453, "EU - 3v3", '3PM EST'],
		'nexus' => ['Fall Frenzy', 'nexus-gaming', 389, 'NA Renegade Cup', '7PM EST'],
		//'nexus' => ['Nexus', 'nexus-gaming', 389, 'NA - 2v2 - $100', '7PM EST'],
		//'cca' => ['CCA', 'cca', 736, "NA - 3v3 - Community Open", '8PM EST'],
		'igl' => ['Indy Gaming League', 'indy-gaming-league', 1544, 'NA - 3v3 - Fall Circuit', '8PM EST'],
		// 'bl' => ['Boost Legacy', 'boost-legacy', 401, 'NA - 1v1', '8PM EST'],
		//'bl' => ['Boost Legacy', 'boost-legacy', 401, 'NA - 3v3 - $30', '9PM EST'],
		// 'astro' => ['ASTRONAUTS', 'teambeyondnet', 540, 'NA - 2v2 - $1,000', '930PM EST'],
		//'RLES' => ['RL ES', 'rocket-league-es', 711, 'EU 3v3 #TGXRLP', '3PM EST'],
		'me' => ['The Dailies', 'rocket-dailies', 688, 'Nom Stream', '6PM EST'],
	),
	'Thursday' => array(
		//'goldenDust' => ['Golden Dust Cup', 'tgx', 916, 'Storm Chaser Championship', '12PM EST'],
		'euccgg' => ['ECC', 'ecc', 1507, 'League Play', '2PM EST'],
		//'rewind' => ['Rewind', 'rewindrl', 583, 'EU - 2v2', '1PM EST'],
		// 'gfinity' => ['GFinity', 'rocket-league-central', 547, 'EU - 3v3 - &pound;400', '1PM EST'],
		'tcs' => ['TCS Esports', 'tcs-esports', 1527, 'EU - 3v3 - League Play', '1PM EST'],
		'rocketeers' => ['The Thunderdome', 'rocketeers', 1577, 'EU Renegade Cup', '1PM EST'],
		//'trrlcs' => ['SubParButInHD', 'subparbutinhd', 697, 'Sub Tournament - &pound;75', '230PM EST'],
		// 'universalOpen' => ['Universal Open', 'faceit', 883, 'EU Closed Qualifiers', '12PM EST'],
		'rstreet' => ['RocketStreet', 'rocketstreet', 518, 'SAM - 2v2', '530PM EST'],
		//'jboi' => ['Johnnyboi_i', 'johnnyboi_i', 215, 'Moneymatches', '6PM EST'],
		//'elevate' => ['Elevate', 'elevate-league', 820, 'NA - All Tiers 3v3 - $100', '7PM EST'],
		'rlpc' => ['RLPC', 'rlpc', 1495, 'NA - League Play', '7PM EST'],
		'nexus' => ['Fall Frenzy', 'nexus-gaming', 389, 'NA Renegade Cup', '7PM EST'],
		//'cumCupNA' => ['Community Cup 1v1', 'community-cup-na', 1306, 'NA - 1v1 - $4,000', '7PM EDT'],
		//'myth' => ['Primal League', 'mythical-esports', 251, 'Primal League', '7PM EST'],
		//'NARLI' => ['Northern Arena', 'northern-arena', 1030, 'NA Qualifiers', '7PM EST'],
		// 'Rival' => ['Summer Open', 'prorl', 81, 'Qualifiers', '7PM EST'],
		// 'Rival' => ['Summer Open', 'prorl', 81, 'Qualifiers', '7PM EST'],
		//'challenger' => ['Challenger Cup', 'elevate-league', 820, 'Elevate Cup', '8PM EST'],
		'infiniteShots' => ['Infinite Shots', 'infinite-shots', 1566, 'NA - 3v3 - $100', '8PM EST'],
		// 'playerOne' => ['Player One Esports', 'player-one-esports', 1500, 'NA - 1v1 - $500', '8PM EST'],
		//'sway' => ['Overtime League', 'sway-esports', 1152, 'Rookie/Semi-Pro League', '8PM EST'],
		//'ace' => ['ACE', 'ascending-champions', 928, 'NA - 3v3 - Champ League', '8PM EST'],
		'uRogue' => ['United Rogue', 'united-rogue', 1292, 'NA Expert League - 3v3', '8PM EST'],
		// '150cc' => ['150cc', '150cc', 1387, 'NA - 3v3', '9PM EST'],
		// 'cca' => ['CCA', 'cca', 736, 'Summer Series Playoffs', '9PM EST'],
		// 'mld' => ['MLD', 'mld', 750, 'Playoffs!', '9PM EST'],
		//'cca' => ['CCA', 'cca', 736, 'League Play', '11PM EST'],
		//'RLES' => ['RL ES', 'rocket-league-es', 711, 'EU 3v3 #TGXRLP', '3PM EST'],
		'me' => ['The Dailies', 'rocket-dailies', 688, 'Nom Stream', '6PM EST'],
	),
	'Friday' => array(
		//'vapour' => ['Vapour Esports', 'vapour-esports', 882, 'OCE - 3v3', '4AM EST'],
		// 'insomnia' => ['UK Masters', 'uk-masters', 1385, 'Insomnia 63 - 3v3', '9AM EST'],
		// 'rlrsEU' => ['EU Rival Series', 'rlcs', 79, 'EU RLRS League Play', '1PM EST'],
		//'rlindia' => ['RLIndia', 'rlindia', 897, 'India - 3v3 - Community Cup', '9AM EST'],
		// 'goldenDust' => ['Golden Dust Cup', 'tgx', 916, 'Golden Dust Cup', '1030AM EST'],
		// 'euccgg' => ['ECC', 'ecc', 1507, 'League Play', '1230PM EST'],
		// 'baguette' => ['Rocket Baguette', 'rocket-baguette', 585, 'RBRS - EU - 3v3', '1PM EST'],
		//'gfinityEU' => ['GFinity (EU)', 'rocket-league-central', 547, 'EU - 3v3 - $250', '1PM EST'],
		//'baguette' => ['Rocket Baguette', 'rocket-baguette', 585, 'EU GFinity, French Cast', '1PM EST'],
		//'NARLI' => ['Northern Arena', 'northern-arena', 1030, 'EU Qualifiers', '1PM EST'],
		//'rocketstreet' => ['RocketStreet', 'rocketstreet', 518, 'SAM - 3v3', '5:30PM EST'],
		'elevate' => ['Elevate', 'elevate-league', 820, 'NA League Play', '7PM EST'],
		// 'worldOfRockets' => ['World of Rockets', 'world-of-rockets', 1360, 'NA - 1v1', '730PM EST'],
		//'federation' => ['RL Federation', 'rocketleaguefederation', 1192, 'NA - 3v3 - $25', '8PM EST'],
		//'UA1' => ['United As 1', 'united-as-1', 1136, 'NA - 3v3 - $60', '8PM EST'],
		'myth' => ['Mythical Esports', 'mythical-esports', 251, 'NA - 3v3', '7PM EST'],
		// 'rlrsNA' => ['NA Rival Series', 'rlcs', 79, 'NA RLRS League Play', '7PM EST'],
		// 'Rival' => ['Summer Open', 'prorl', 81, 'Swiss System', '7PM EST'],
		'ucs' => ['UCS Gaming', 'ucsgaming', 847, 'NA - 2v2', '7PM EST'],
		//'sway' => ['Overtime League', 'sway-esports', 1152, 'Pro League Quals', '8PM EST'], 
		//'ace' => ['ACE', 'ascending-champions', 928, 'NA - 2v2 Challenger League', '8PM EST'],
		// 'mld' => ['MLD', 'mld', 750, 'NA - 2v2', '9PM EST'],
		//'cca' => ['CCA', 'cca', 736, 'Friday Night Lights', '830PM EST'],
		//'rlu' => ['RLU', 'rlu', 762, 'NA - 2v2', '11PM EST'],
//Turn On		
		'me' => ['The Dailies', 'rocket-dailies', 688, 'Nom Stream', '6PM EST'],
	),
	'Weekend' => array(
		//'jboi' => ['Johnnyboi_i', 'johnnyboi_i', 215, 'NA 1v1 Grand Finals', '12PM EST'],
		// '1ne' => ["1NE Esports", "1ne-esports", 1113, 'Asia Pro League 2 - $3,000', 'SAT 2AM EST'],		
		//'gfinityAUS' => ['A Tournament', 'byza', 1171, 'OCE - 3v3 - $350', 'SAT 330AM EST'],
		//'dreamhack' => ['Dreamhack Leipzig', 'dreamhack', 727, '$50,000 LAN', 'SAT 7AM EST'],
		// 'euroRLSAT' => ['EuroRL', 'euro-rl', 1491, 'Playoffs!', 'SAT 8AM EST'],
		//'gfinityElite' => ['GFinity', 'gfinity', 194, 'GFinity Elite Series Finals', 'SAT 8AM EST'],
		//'rlindiaSAT' => ['RLIndia', 'rlindia', 897, 'India - 3v3 - Community Cup', 'SAT 9AM EST'],
		// 'insomnia' => ['UK Masters', 'uk-masters', 1385, 'Insomnia 63 - 3v3', 'SAT 9AM EST'],
		'euccgg' => ['ECC', 'ecc', 1507, 'EU - League Play', 'SAT 9AM EST'],
		//'metaleak' => ['Metaleak', 'metaleak', 521, 'EU - 2v2 - &euro;50', '10AM EST'],
		// 'goldenDust' => ['Golden Dust Cup', 'tgx', 916, 'Golden Dust Cup', 'SAT 1030AM EST'],
		'trekza' => ['DesafioNZXT', 'trekza', 1545, 'EU - 3v3 - League Play', 'SAT 11AM EST'],
		// 'rivalEU' => ['Rival Esports', 'prorl', 81, 'EU - $150 - 3v3', 'SAT 12PM EST'],
		'rivalEU' => ['Rivals Cup', 'prorl', 81, 'EU - $150 - 3v3', 'SAT 1130AM EST'],
		'rhlSAT' => ['RHL', 'rocket-hockey-league', 1053, 'Season 3 Playoffs!', 'SAT 2PM EST'],
		'flgSat' => ['Frontline Gaming', 'frontline-gaming', 1572, 'Challenger League Playoffs', 'SAT 230PM EST'],
		// 'rlcsNA' => ['RLCS NA', 'rlcs', 79, 'NA Regional Championship', 'SAT 3PM EST'],
		'fancy' => ['Team Fancy', 'team-fancy', 1502, 'NA - 3v3 - $100', 'SAT 4PM EST'],
		//'powered' => ['Rocket Powered', 'rocket-powered', 826, 'NA - 2v2 - $30', 'SAT 2PM EST'],
		// 'rlHub' => ['RL Hub', 'rl-hub', 1203, 'NA - 2v2 - $30', 'SAT 2PM EST'],
		// 'universalOpen' => ['Universal Open', 'faceit', 883, 'West Regional Finals', 'SAT 2PM EST'],
		//'ballistix' => ['Ballistix Gaming', 'ballistix', 1372, 'EU - $500 & Qualifiers', 'SAT 1PM EST'],
		//'snowDay' => ['Snow Day', 'snow-day-community', 1166, 'Snow Day Underpass', 'SAT 4PM EST'],
		// 'forzen' => ['Forzen Esports', 'forzen', 772, 'NA - 3v3 - Plat Cup', 'SAT 4PM EST'],	
		//'ccaSAT' => ['CCA', 'cca', 736, 'College Invitational #1', 'SAT 3PM EST'],
	//	'astro' => ['ASTRONAUTS', 'teambeyondnet', 540, 'NA - 3v3 - $2,000', '7PM EST'],
		'elevateSat' => ['Elevate', 'elevate-league', 820, 'Tier 3 League', 'SAT 7PM EST'],
		// 'throwdown' => ['Throwdown TV', 'throwdowntv', 531, 'OCE Playoffs', 'SAT 8PM EST'],
		'gfinityAU' => ['GFinityAU', 'gfinityau', 1401, 'Elite Series LAN', 'SAT 8PM EST'],	
		// 'flightclub' => ['Flight Club', 'flight-club', 855, 'NA - 1v1', 'SAT 7PM EST'],
		//'ace' => ['ACE', 'ascending-champions', 928, 'NA - 3v3 Challenger League', '8PM EST'],
		'mldSat' => ['MLD', 'mld', 750, 'NA - 2v2', 'SAT 8PM EST'],
		//'vapour' => ['Vapour Esports', 'vapour-esports', 882, 'VN-League Playoffs', 'SAT 8PM EST'],
		// 'vapour' => ['Vapour Esports', 'vapour-esports', 882, 'OCE - 1v1 - $95 AUD', 'SUN 2AM EST'],
		// 'rlo' => ['Rocket League Oceania', 'rocket-league-oceania', 646, 'OCE - 3v3 - $100', '5AM EST'],
		//'dreamhackSUN' => ['Dreamhack Leipzig', 'dreamhack', 727, '$50,000 LAN', 'SUN 5AM EST'],
		//'rlindiaSUN' => ['RLIndia', 'rlindia', 897, 'India - 3v3 - $500', 'SUN 6AM EST'],
		//'ireland' => ['RL Ireland', 'rocket-league-ireland', 1115, 'EU - 3v3', 'SUN 9AM EST'],
		// 'euroRLSUN' => ['EuroRL', 'euro-rl', 1491, 'Playoffs!', 'SUN 10AM EST'],
		// 'rlcsEU' => ['RLCS EU', 'rlcs', 79, 'EU Regional Championship', 'SUN 12PM EST'],
	//	'rlHub' => ['RL Hub', 'rl-hub', 1203, 'NA - 1v1 - $20', 'SUN 1PM EST'],
		// 'cca' => ['CCA', 'cca', 736, 'Summer Series League Play', 'SUN 2PM EST'],
		//'UERLA' => ['UERLA', 'uerla-league', 1123, 'EU - 3v3 - League Play', 'SUN 2PM EST'],
		//'diamondDuels' => ['Diamond League', 'diamond-duels', 1177, 'EU - 3v3 - League Play', 'SUN 1PM EST'],
		'rhlSUN' => ['RHL', 'rocket-hockey-league', 1053, 'Season 3 Playoffs!', 'SUN 2PM EST'],
		'flgSun' => ['Frontline Gaming', 'frontline-gaming', 1572, 'Challenger League Playoffs', 'SUN 230PM EST'],
		//'mindGames' => ['MindGames Esports', 'mindgames-esports', 777, 'EU - 2v2 - $100', 'SUN 3PM EST'],
		// 'texasRL' => ['Texas RL', 'texasrl', 486, 'Shadowlan', 'SUN 3PM EST'],
		//'uRogueEU' => ['United Rogue', 'united-rogue', 1292, 'EU League - 3v3', 'SUN 3PM EST'],
		//'ccaSUN' => ['CCA', 'cca', 736, 'Spring Series Championship', 'SUN 3PM EST'],
		'rstreet' => ['Rocket Street Grind', 'rocketstreet', 518, 'SAM - 3v3 - $1000', 'SUN 4PM EST'],
		// 'nexus' => ['Nexus', 'nexus-gaming', 389, 'The Final Bracket', 'SUN 6PM EST'],
		'hoopsNA' => ['Ranked Hoops', 'ranked-hoops', 837, 'NA - Hoops', 'SUN 7PM EST'],
		//'elevateSun' => ['Elevate', 'elevate-league', 820, 'NA - 3v3', 'SUN 7PM EST'],
		'uRogueNA' => ['United Rogue', 'united-rogue', 1292, 'NA Master League - 3v3', 'SUN 8PM EST'],
		'mldSun' => ['MLD', 'mld', 750, 'NA - 2v2', 'SUN 8PM EST'],
		'me' => ['The Dailies', 'rocket-dailies', 688, 'Nom Stream', 'SUN 6PM EST'],
	),
); 

$latestNomArgs = array(
	'category_name' => 'noms',
	'posts_per_page' => 1,
);
$latestNom = get_posts($latestNomArgs);
$latestNomTime = strtotime($latestNom[0]->post_date);
$latestNomDay = date('l', $latestNomTime);
$latestNomDate = date('j', $latestNomTime);
$latestNomDateSuffix = date('S', $latestNomTime);
$latestNomMonth = date('F', $latestNomTime);
$latestNomYear = date('Y', $latestNomTime);
if ($latestNomDay == 'Saturday' || $latestNomDay == 'Sunday') {
	$todaysSchedule = 'Weekend';
} else {
	$todaysSchedule = $latestNomDay;
}

$myWeekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Weekend'];
$todaysKey = array_search($todaysSchedule, $myWeekdays);

$shiftedWeek = [];
for ($i=$todaysKey; $i <= 5; $i++) { 
	$shiftedWeek[] = $myWeekdays[$i];
};
for ($i=0; $i < $todaysKey; $i++) { 
	$shiftedWeek[] = $myWeekdays[$i];
};

$shiftedSchedule = [];
foreach ($shiftedWeek as $key => $dayName) {
	$shiftedSchedule[$dayName] = $schedule[$dayName];
};

?>